worker_processes 2;
user www-data;

events {
    use epoll;
    worker_connections  128;
}

http {
    server_tokens off;
    include       /etc/nginx/mime.types;
    charset       utf-8;

    limit_req_zone $binary_remote_addr zone=login:10m rate=50r/s;
    limit_conn_zone $binary_remote_addr zone=addr:10m;

    include /etc/nginx/conf.d/*.conf;
}